### ISSUE TITLE
Nil Values

### ISSUE THREAD

**Issue by Neilfau** [sxg/ForecastIO#58]
Ive noticed since updating to the latest version a lot of values are now nil all the time. All the precipitation values, temperatures low/high etc. Some data is being decoded but not all of it.

**Comment by sxg** [comment]
Ah damn. I thought things were ok with the unit tests. I’ll take a look at this later this evening and try to submit an update ASAP.

**Comment by Neilfau** [comment]
Ok thanks!

**Comment by sxg** [comment]
I'm currently working on this, and I realized that the JSON keys for some of the precipitation values differ from the property names I specified, which explains that issue. Are you seeing other data that exists in the JSON but not in ForecastIO? I'm searching for other errors but not coming up with much.

Additionally, `Flag.nearestStation` is not always included in the JSON response despite DarkSky's API noting it as a required property. I'll reach out to them and see if that's a documentation or service bug.

**Comment by Neilfau** [comment]
I think it was mainly precipitation and temperature high / lows were the main problem, but I didn't have time to investigate into too much detail.

**Comment by sxg** [comment]
I checked the temperature values, and I was able to confirm that those fields are being populated. They are optional properties, so they may not always be there on all requests. The main issue I saw was with the precipitation properties, which are now fixed in 6.0.1. Let me know if you run into more discrepancies between the JSON response and ForecastIO, and thanks for bringing this to my attention!
